name: md_example_inserter
version: 0.0.1
description: Inserts the code from the example in the file specified in the `{@example paht/to/file}` tag.
author: Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/luisvt/md_example_inserter

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  glob: ^1.1.3
  path: ^1.4.1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

executables:
  md_example_inserter: main